wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.15
    start_time: 1660911815
    t:
      1:
      - 1
      - 5
      3:
      - 15
      - 23
      4: 3.6.15
      5: 0.13.1
      8:
      - 3
      - 5
